responders:
  - responder:
    request: default
    class: DefaulTop
    permissions:
    - any

  - responder:
    request: maintenance
    class: Maintenance
    permissions:
    - any

  - responder:
    request: info/sys
    class: Info
    permissions:
    - any
  - responder:
    request: info/client
    class: ClientInfo
    permissions:
    - any
